title: Ashes & Ink
description: A blog by dark romance author Jamie McCann.
baseurl: "" 
url: "https://jmccann917.github.io/Jamiemccann"
theme: minima
sass:
  style: compressed
markdown: kramdown
plugins:
  - jekyll-feed
encoding: "utf-8"
